#!/bin/sh
set -e

. "$2"

url="https://ftp.gnu.org/gnu/coreutils/coreutils-9.9.tar.gz"

configure() {
    ./configure --prefix="/usr" --disable-static --enable-shared
}

build() {
    make -j$(nproc)
}

install() {
    make DESTDIR="$1" install
}

export CFLAGS="-O2"
export CXXFLAGS="$CFLAGS"

start_installation "$1" "$url"
