#!/bin/sh
set -e

. "$2"

url="https://github.com/nghttp2/nghttp2/releases/download/v1.68.0/nghttp2-1.68.0.tar.gz"

configure() {
    ./configure --prefix="/usr" --disable-static --enable-shared
}

build() {
    make -j$(nproc)
}

install() {
    make DESTDIR="$1" install
}

export CFLAGS="-O2"
export CXXFLAGS="$CFLAGS"

start_installation "$1" "$url"
