#!/bin/sh
set -e

. "$2"

url="https://sourceware.org/pub/bzip2/bzip2-1.0.8.tar.gz"

configure() {
    :
}

build() {
    make -j$(nproc)
    make -f Makefile-libbz2_so -j$(nproc)
}

install() {
    make PREFIX=/usr DESTDIR="$1" install
    cp -v libbz2.so.1.0 "$1/usr/lib/"    
}

export CFLAGS="-O2 -fPIC"
export CXXFLAGS="$CFLAGS"

start_installation "$1" "$url"
