#!/bin/sh
set -e

. "$2"

url="https://astron.com/pub/file/file-5.46.tar.gz"

configure() {
    ./configure --prefix=/usr --disable-static
}

build() {
    make -j$(nproc)
}

install() {
    make DESTDIR="$1" install
}

export CFLAGS="-O2"
export CXXFLAGS="$CFLAGS"

start_installation "$1" "$url"
