#!/bin/sh

# $1 - dest, all packages are defaulted to /usr , $2 - sh file which include all functions

. "$2"

url="https://ftp.gnu.org/gnu/libc/glibc-2.42.tar.gz"

configure() {
    mkdir -p glibc-build
    cd glibc-build
    ../configure --prefix="/usr"
}

build() {
    cd glibc-build
    make -j$(nproc)
}

install() {
    cd glibc-build
    make install DESTDIR="$1"
}

start_installation "$1" "$url"