#!/bin/sh

# $1 - dest, all packages are defaulted to /usr , $2 - sh file which include all functions

. "$2"

url="https://ftpmirror.gnu.org/libc/glibc-2.42.tar.gz"

configure() {
    mkdir -p glibc-build
    cd glibc-build
    ../configure --prefix="/usr" --disable-debug --disable-nls --disable-profile
}

build() {
    cd glibc-build
    make -j$(nproc)
}

install() {
    cd glibc-build
    make install DESTDIR="$1"
    cd "$1"
    rm -rf lib lib64 bin
    echo "Creating symlinks"
    mkdir -p usr/lib
    ln -sf usr/lib lib
    ln -sf usr/lib64 lib64
    ln -sf usr/bin bin
}

export CFLAGS="-O2"
export CXXFLAGS="$CFLAGS"

start_installation "$1" "$url"