#!/bin/sh
set -e

# $1 - dest, all packages are defaulted to /usr , $2 - sh file which include all functions

. "$2"

url="https://ftp.gnu.org/gnu/libc/glibc-2.42.tar.gz"

configure() {
    mkdir -p glibc-build
    cd glibc-build
    ../configure --prefix="/usr" --disable-debug --disable-nls --disable-profile --libdir=/usr/lib --disable-static --enable-shared
}

build() {
    cd glibc-build
    make -j$(nproc)
}

install() {
    cd glibc-build
    make DESTDIR="$1" install
    cd "$1"
    rm -rf lib bin
    echo "Creating symlinks"
    mkdir -p usr/lib
    mkdir -p usr/lib64
    mkdir -p usr/sbin
    ln -sf usr/lib lib
    ln -sf usr/bin bin
    ln -sf usr/sbin sbin
    cd usr
    rm -rf lib64
    ln -sf lib lib64
}

export CFLAGS="-O2"
export CXXFLAGS="$CFLAGS"

start_installation "$1" "$url"