#!/bin/sh
set -e

. "$2"

url="https://github.com/mirror/ncurses/archive/refs/tags/v6.4.tar.gz"

configure() {
    ./configure --prefix="/usr" --with-shared --without-normal --enable-widec --with-versioned-syms
}

build() {
    make -j$(nproc)
}

install() {
    make DESTDIR="$1" install
}

export CFLAGS="-O2"
export CXXFLAGS="$CFLAGS"

start_installation "$1" "$url"
