#!/bin/sh
set -e

. "$2"

url="https://github.com/ferris-linux/ferris-linux/releases/download/Binaries/vmlinuz"

configure() {
    :
}

build() {
    :
}

install() {
    mkdir -p "$1/boot"
    wget -O "$1/boot/vmlinuz" "$url"
}

install "$1"