#!/bin/sh

. "$2"

url="https://cdn.kernel.org/pub/linux/kernel/v6.x/linux-6.18.3.tar.xz"

configure() {
    cp -rf "$script_dir/.config" ".config"
}

build() {
    yes | make -j$(nproc)
}

install() {
    yes | make INSTALL_PATH="$1/boot" install -j$(nproc)
}

export CFLAGS="-O2"
export CXXFLAGS="$CFLAGS"

start_installation "$1" "$url"
