#!/bin/sh
set -e

. "$2"

url="https://github.com/iputils/iputils/releases/download/20250605/iputils-20250605.tar.gz"

configure() {
    ./configure --prefix="/usr" --disable-static --enable-shared
}

build() {
    make -j$(nproc)
}

install() {
    make DESTDIR="$1" install
}

export CFLAGS="-O2"
export CXXFLAGS="$CFLAGS"

start_installation "$1" "$url"
