#!/bin/sh
set -e

. "$2"

url="https://github.com/zyedidia/micro/archive/refs/tags/v2.0.15.tar.gz"

configure() {
    :
}

build() {
    make build
}

install() {
    cp micro "$1/usr/bin/micro"
}

export CFLAGS="-O2"
export CXXFLAGS="$CFLAGS"

start_installation "$1" "$url"
