#!/bin/sh
set -e

. "$2"

url="https://github.com/uutils/coreutils/archive/refs/tags/0.5.0.tar.gz"

configure() {
    :
}

build() {
    make PROFILE=release-fast
}

install() {
    make PROFILE=release-fast DESTDIR="$1" install
}

export CFLAGS="-O2"
export CXXFLAGS="$CFLAGS"

start_installation "$1" "$url"
