#!/bin/sh

. "$2"

url="https://ftp.gnu.org/gnu/bash/bash-5.3.tar.gz"

configure() {
    ./configure --prefix="/usr" --without-bash-malloc --disable-readline --with-curses 
}

build() {
    make -j$(nproc)
}

install() {
    make DESTDIR="$1" install
    cd "$1/usr/bin"
    ln -s bash sh
}

export CFLAGS="-O2"
export CXXFLAGS="$CFLAGS"
start_installation "$1" "$url"