#!/bin/sh
set -e

. "$2"

url="https://ftp.gnu.org/gnu/bash/bash-5.3.tar.gz"

configure() {
    export CPPFLAGS="-I/usr/include"
    export LDFLAGS="-L/usr/lib"

    ./configure --prefix="/usr" --without-bash-malloc --with-installed-readline
}

build() {
    make -j$(nproc)
}

install() {
    make DESTDIR="$1" install
    ln -sf bash "$1/usr/bin/sh"
}

export CFLAGS="-O2"
export CXXFLAGS="$CFLAGS"

start_installation "$1" "$url"
