#!/bin/sh

. "$2"

url="https://ftpmirror.gnu.org/gnu/bash/bash-5.3.tar.gz"

configure() {
    ./configure --prefix="/usr" --without-bash-malloc --disable-readline --with-curses 
}

build() {
    make -j$(nproc)
}

install() {
    make install DESTDIR="$1"
}

start_installation "$1" "$url"