#!/bin/sh

. "$2"

url="https://curl.se/download/curl-8.17.0.tar.gz"

configure() {
    ./configure \
        --prefix="/usr" \
        --disable-static \
        --enable-shared \
        --with-ssl \
        --with-zlib \
        --with-libidn2 \
        --disable-manual
}

build() {
    make -j$(nproc)
}

install() {
    make install DESTDIR="$1"
}

export CFLAGS="-O2"
export CXXFLAGS="$CFLAGS"

start_installation "$1" "$url"
