#!/bin/sh
set -e

. "$2"

url="https://ftp.gnu.org/gnu/wget/wget-1.25.0.tar.gz"

configure() {
	./configure --prefix=/usr --with-ssl=openssl
}

build() {
	make -j$(nproc)
}

install() {
	make DESTDIR="$1" install
}

export CFLAGS="-O2"
export CXXFLAGS="$CFLAGS"

start_installation "$1" "$url"
