#!/bin/sh
set -e

. "$2"

url="https://www.openssl.org/source/openssl-3.6.0.tar.gz"

configure() {
    ./Configure \
        linux-$(uname -m) \
        --prefix=/usr \
        --libdir=lib \
        shared \
        zlib \
        -Wl,-rpath,/usr/lib
}

build() {
    make -j$(nproc)
}

install() {
    make DESTDIR="$1" install_sw
}

export CFLAGS="-O2"
export CXXFLAGS="$CFLAGS"

start_installation "$1" "$url"
