#!/bin/sh

. "$2"

url="https://www.openssl.org/source/openssl-3.6.0.tar.gz"

configure() {
    ./Configure \
        linux-x86_64 \
        --prefix=/usr \
        --libdir=lib \
        shared \
        zlib \
        -Wl,-rpath,/usr/lib
}

build() {
    make -j$(nproc)
}

install() {
    make install_sw DESTDIR="$1"
}

export CFLAGS="-O2"
export CXXFLAGS="$CFLAGS"

start_installation "$1" "$url"
