#!/bin/sh
set -e

. "$2"

url="https://codeload.github.com/util-linux/util-linux/tar.gz/refs/tags/v2.41.3"

configure() {
    ./autogen.sh
    ./configure \
        --prefix="/usr"
}

build() {
    make -j$(nproc)
}

install() {
    make DESTDIR="$1" install
}

export CFLAGS="-O2"
export CXXFLAGS="$CFLAGS"

start_installation "$1" "$url"
